"""Compile the real credit-extra worker against Android JSON signatures, replay fake RPC only."""
from pathlib import Path
import os, re, subprocess, tempfile

root = Path(__file__).resolve().parents[1]
pkg = 'io.github.aw1y2z.sesame'
source = root / 'app/src/main/java'
worker = source / pkg.replace('.', '/') / 'model/task/goldenbeans/SesameCreditExtras.java'
stubs = {
 'util.MyUtils': '''import java.util.*;import org.json.*;public class MyUtils {
 public static int offset;public static Calendar getInstance(){Calendar c=Calendar.getInstance(TimeZone.getTimeZone("GMT+8"));c.setTimeInMillis(1791300600000L+offset*86400000L);return c;}
 public static JSONObject newJSONObject(){return new JSONObject();}public static JSONObject newJSONObject(String s){try{return new JSONObject(s);}catch(Exception e){return new JSONObject();}}}''',
 'util.TimeUtil': '''public class TimeUtil {public static boolean cancel;public static long waited;public static int interruptAt;public static String interrupt="";public static Runnable drift=()->{};
 public static void sleep(long n){if(cancel)throw new TaskCancelledException();waited+=n;if(interruptAt>0&&waited>=interruptAt){if(interrupt.equals("uid"))io.github.aw1y2z.sesame.util.idMap.UserIdMap.uid="B";else if(interrupt.equals("day"))MyUtils.offset=1;else if(interrupt.equals("durationDrift"))drift.run();else cancel=true;interruptAt=0;}}}''',
 'util.Log': '''public class Log {public static int confirmed;public static java.util.List<String> messages=new java.util.ArrayList<>();public static void other(String s){messages.add(s);if(s.startsWith("\u829d\u9ebb\u989d\u5916\u4efb\u52a1"))confirmed++;}public static void record(String s){}public static void error(String s){messages.add(s);}public static void i(String s){messages.add(s);}public static void err(String t,String s,Throwable e){throw new AssertionError(e);}}''',
 'util.idMap.UserIdMap': '''public class UserIdMap {public static String uid="A";public static String getCurrentUid(){return uid;}}''',
 'rpc.intervallimit.RpcRequestGuard': '''import org.json.*;public class RpcRequestGuard {public static boolean isFailure(JSONObject j){return Boolean.FALSE.equals(j.opt("success"))||"FAIL".equals(j.opt("resultCode"));}}''',
 'data.RuntimeInfo': '''import java.util.*;public class RuntimeInfo {public static boolean writable=true;public static Map<String,RuntimeInfo> users=new HashMap<>();private Map<String,String> values=new HashMap<>();public static RuntimeInfo getInstance(){return users.computeIfAbsent(io.github.aw1y2z.sesame.util.idMap.UserIdMap.uid,k->new RuntimeInfo());}public String getString(String k){return values.getOrDefault(k,"");}public boolean putVerified(String k,String v){if(!writable)return false;values.put(k,v);return true;}}''',
 'hook.AuthCodeHelper': '''public class AuthCodeHelper {public static String code="auth-code";public static String getAuthCode(String appId){io.github.aw1y2z.sesame.model.task.goldenbeans.SesameCheck.SDK.auth();return code;}}''',
 'hook.ApplicationHook': r'''import org.json.*;import java.util.*;import io.github.aw1y2z.sesame.util.*;public class ApplicationHook {
 public static long getAlipayVersion(){return 1000;}public static JSONObject home,rent,alchemy,credit,time,award;public static List<String> calls=new ArrayList<>();public static int mutations,queries,creditQueries;public static boolean treeDelegateEffect=true,delegateDrift;public static String resultDrift="";
 public static boolean effect=true,ack=true,readback=true,nested,drift,uidAfter,cancelAfter;public static String bad="",failOp="",treeAdReadback="",durationMode="",channelMode="";public static int timeState=2,consultCount;
 public static JSONObject ok(){return new JSONObject().put("success",true).put("resultCode",200);}
 public static JSONObject copy(JSONObject j){return new JSONObject(j.toString());}
 public static String p2eMode="";public static int p2eSeconds=90,reported;public static List<Integer> chunks=new ArrayList<>();
 static void p2eGame(JSONObject a){assert a.optString("source").equals("p2e\"source")&&a.optString("gameId").equals("p2e-game")&&a.optString("gameModuleId").equals("p2e-module");}
 public static String requestString(String m,String a){return call(m,a,false);}
 public static String requestString(String m,String a,int n,int d){assert n==1&&d==0:"mutation bridge retry";return call(m,a,true);}
 public static JSONArray rows(){return home.optJSONArray("browseTaskList");}public static JSONArray alchemyRows(){return alchemy.optJSONArray("toCompleteVOS");}
 public static JSONObject treeFind(String id){for(JSONArray a:new JSONArray[]{rows(),rent.optJSONArray("taskDetailList")})for(int i=0;i<a.length();i++){JSONObject r=a.optJSONObject(i);if(id.equals(r.optJSONObject("taskBaseInfo").optString("appletId")))return r;}throw new AssertionError(id);}
 public static JSONObject alcFind(String id){for(JSONArray rows:new JSONArray[]{alchemyRows(),credit.optJSONArray("toCompleteVOS")})for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(id.equals(r.optString("templateId"))||id.equals(r.optJSONObject("logExtMap")==null?"":r.optJSONObject("logExtMap").optString("bizId"))||id.equals(r.optString("recordId")))return r;}throw new AssertionError(id);}
 static String call(String method,String raw,boolean mutation){
  JSONObject args=new JSONArray(raw).optJSONObject(0);String op=method.substring(method.lastIndexOf('.')+1);if(op.equals("trigger"))op=args.optString("operationCode");calls.add(op);if(mutation)mutations++;else queries++;
  if(!mutation&&(!readback&&mutations>0||op.equals(failOp)))return "garbage";
  JSONObject result=ok();
  if(op.equals("ZHIMA_TREE_HOME_PAGE"))result.put("extInfo",new JSONObject().put("zhimaTreeHomePageQueryResult",copy(home)));
  else if(op.equals("RENT_GREEN_TASK_LIST_QUERY"))result.put("extInfo",new JSONObject().put("taskDetailList",copy(rent)));
  else if(op.equals("RENT_GREEN_TASK_FINISH")){
   assert mutation;String id=args.optString("taskId"),stage=args.optString("stageCode");JSONObject ext=args.optJSONObject("extInfo");assert ext.opt("taskId").equals(id)&&ext.opt("stageCode").equals(stage);
   assert ext.optString("chInfo").equals("context\"channel");assert args.optString("refer").equals("context-refer");assert args.optString("playInfo").equals("context-play");
   JSONObject r=treeFind(id);if(r.optString("taskChannel").equals("RENT")){assert args.optString("userId").equals("A")&&ext.optString("userId").equals("A");assert args.optString("appletId").equals("dynamic-app")&&ext.optString("appId").equals("dynamic-app");}
   JSONObject material=r.optJSONObject("taskMaterial");if(stage.equals("send")&&material!=null&&material.optString("taskType").equals("BROWSER"))assert TimeUtil.waited==material.optInt("browseTime")*1000L:"browser sent before its full countdown";
   if(effect)r.put("taskProcessStatus",stage.equals("signup")?"SIGNUP_COMPLETE":stage.equals("send")?"TO_RECEIVE":"RECEIVED");
  }
  else if(op.equals("ZHIMA_TREE_CLEAN_AND_PUSH")){
   assert mutation;JSONObject ext=args.optJSONObject("extInfo");assert ext.optString("treeCode").equals("server-tree")&&ext.optString("clickNum").equals("1");
   if(effect){JSONArray g=home.optJSONObject("garbageMap").optJSONArray("type");for(int i=0;i<g.length();i++)if(ext.opt("clearArea").equals(g.optJSONObject(i).opt("subType"))){g.remove(i);break;}home.put("purificationScore",home.optInt("purificationScore")-100);JSONObject t=home.optJSONArray("trees").optJSONObject(0);t.put("remainPurificationClickNum",t.optInt("remainPurificationClickNum")-1);}
  }
  else if(op.equals("queryListV3")){if(args.optString("version").equals("new")){assert args.optString("sceneCode").equals("DAILY_MUST_DO_CARD")&&args.optBoolean("searchAddToHomeTask")&&args.optBoolean("supportJumpAuth");creditQueries++;if(delegateDrift&&creditQueries==2)credit.optJSONArray("toCompleteVOS").optJSONObject(0).put("appId","changed-app");result.put("data",copy(credit));}else{assert args.optString("version").equals("alchemy")&&args.optBoolean("supportRewardLJCS");if(drift&&queries==2)alchemyRows().optJSONObject(0).put("title","changed");result.put("data",copy(alchemy));}}
  else if(op.equals("joinActivity")){assert args.optString("sceneCode").equals("alchemy")&&!args.optBoolean("joinFromOuter")&&args.optString("chInfo").equals("seasameList");String id=args.optString("templateId");result.put("data",new JSONObject().put("recordId","record\""+id));if(effect)alcFind(id).put("recordId","record\""+id);}
  else if(op.equals("actionSubmit")){assert mutation&&args.length()==2&&args.optString("type").equals("actionSubmit")&&args.optString("chInfo").equals("chInfo=ch_zmzltf__chsub_zmlrw");}
  else if(method.contains(".p2e.")&&List.of("queryHomePage","queryTaskList","queryFeedsGameList").contains(op)){
   assert !mutation&&args.length()==4&&args.optString("source").equals("p2e\"source")&&args.optString("opaque").equals(op)&&args.optJSONArray("unknown").optJSONObject(0).optBoolean("preserve")&&args.optInt("zero")==0;
   JSONObject game=new JSONObject().put("appId",p2eMode.equals("gameDrift")&&TimeUtil.waited>0?"changed":"p2e-app").put("gameId","p2e-game").put("moduleId","p2e-module").put("version",p2eMode.equals("versionDrift")&&TimeUtil.waited>0?"v2":"v1");JSONArray games=new JSONArray();
   if(!p2eMode.equals("noGame"))games.put(game);if(p2eMode.equals("ambiguous"))games.put(copy(game).put("appId","another"));if(p2eMode.equals("incomplete")||p2eMode.equals("entryFallback"))game.remove("version");if(p2eMode.equals("entryFallback"))game.remove("moduleId");if(p2eMode.equals("owner"))game.put("userId","B");result.put("data",new JSONObject().put("pages",new JSONArray().put(new JSONObject().put("games",games))));
  }
  else if(op.equals("submitEvent")){assert mutation&&args.optString("appId").equals("p2e-app")&&args.optString("source").equals("p2e\"source");JSONObject attrs=args.optJSONObject("eventAttrMap");assert attrs.length()==7&&attrs.optString("GAME_VERSION").equals("v1")&&attrs.optString("SCENE_ID").equals("p2e-channel")&&attrs.optString("CH_INFO").equals("p2e\"source")&&attrs.optString("PALADINX_VERSION").equals("2.2.5");String event=args.optString("eventId");assert event.equals(countEvents()==1?"GAME_FIRST_FRAME":"loading_completed")&&args.optString("idempotentNo").endsWith(event.equals("GAME_FIRST_FRAME")?"_p2e-app_first_frame":"_p2e-app_1");if(p2eMode.equals("loadingFail")&&event.equals("loading_completed"))return "garbage";}
  else if(op.equals("submitUserAction")){assert mutation&&args.length()==4&&args.optString("gameId").equals("p2e-app")&&args.optString("actionCode").equals("enterGame")&&args.optString("source").equals("gameFramework")&&args.optString("paladinxVersion").equals("2.2.5");}
  else if(op.equals("consult")&&method.contains("GameAssistantRpc")){assert !mutation&&args.optString("appId").equals("p2e-app")&&args.optString("assistantVersion").equals("3.0.0")&&args.optString("sceneCode").equals("GAME_MSG");}
  else if(op.equals("consultGameComponent")||op.equals("queryGameComponent")){assert !mutation&&args.optString("appId").equals("p2e-app")&&args.optString("channel").equals("p2e-channel")&&args.optString("scene").equals("p2e-scene")&&args.optString(op.equals("queryGameComponent")?"chInfo":"source").equals("p2e\"source");if(op.equals("queryGameComponent")){boolean head=calls.stream().filter(op::equals).count()==2;assert args.opt("setHead").equals(head)&&args.optString("sourceTab").equals("buoy")&&args.optString("reqType").equals(head?"":"START_APP_FIRST_REQ")&&args.has("panelLaunchableCheckMap")!=head;}if(p2eMode.equals("initFail"))return "garbage";}
  else if(op.equals("gameP2eFloatingBallConsult")){assert !mutation&&args.length()==5&&args.optString("__git").equals("9e159d58cce04c13a")&&args.optString("trafficDriverId").equals("p2e-driver");p2eGame(args);Object sec=p2eSeconds;if(p2eMode.equals("timeType"))sec="90";if(p2eMode.equals("fraction"))sec=90.1;if(p2eMode.equals("timeDrift")&&TimeUtil.waited>0)sec=p2eSeconds+1;result.put("data",new JSONObject().put("floatingBallVO",new JSONObject().put("timeSeconds",sec)));if(p2eMode.equals("typeDrift")&&TimeUtil.waited>0)result.optJSONObject("data").optJSONObject("floatingBallVO").put("floatingBallTypeList",new JSONArray().put("UNKNOWN"));if(p2eMode.equals("consultAck"))result.remove("success");}
  else if(op.equals("submitUserPlayDurationAction")&&args.optString("source").equals("p2e\"source")){assert mutation&&args.length()==4&&args.optString("gameAppId").equals("p2e-app")&&args.optString("statisticTag").isEmpty();int n=args.optInt("playTime");assert n==Math.min(reported==0?31:30,p2eSeconds+1-reported)&&TimeUtil.waited==(reported+n)*1000L;reported+=n;chunks.add(n);if(p2eMode.equals("durationFail")||p2eMode.equals("chunk2Fail")&&chunks.size()==2)return "garbage";if(p2eMode.equals("durationAck"))result.remove("success");}
  else if(op.equals("gameP2eFloatingBallComplete")){assert mutation&&args.length()==6&&reported==p2eSeconds+1&&TimeUtil.waited==reported*1000L&&args.optString("trafficDriverId").equals("p2e-driver")&&args.optString("oriChInfo").equals("ori\"channel")&&args.optJSONArray("floatingBallTypeList").toString().equals("[\"P2E_GAME_BROWSE_TASK_FLOATING_BALL\"]");p2eGame(args);if(p2eMode.equals("completeFail"))return "garbage";if(effect)alchemyRows().optJSONObject(0).put("completedNum",1).put("finishFlag",true);if(p2eMode.equals("recordDrift"))alchemyRows().optJSONObject(0).put("recordId","other");if(p2eMode.equals("completeAck"))result.remove("success");}
  else if(op.equals("queryHomePage")&&method.contains("external.gamecenter")){assert !mutation&&args.optString("__git").equals("9e159d58cce04c13a")&&args.optString("sceneId").equals("scene\"id")&&args.optString("moduleId").equals("module-id")&&args.optString("guideType").equals("guide-id")&&args.optString("source").equals("source\"channel");JSONObject pass=new JSONObject(args.optString("channelTaskPassThrough"));assert pass.optString("sceneId").equals("scene\"id")&&pass.optString("taskId").equals("channel-task");if(channelMode.equals("homeFail"))return "garbage";}
  else if(op.equals("queryRecommendGames")){assert !mutation&&args.optString("sceneId").equals("scene\"id")&&args.optString("source").equals("source\"channel");JSONArray games=new JSONArray();if(!channelMode.equals("noGame"))games.put(new JSONObject().put("appId",channelMode.equals("gameDrift")&&TimeUtil.waited>0?"changed":"dynamic-game"));result.put("data",new JSONObject().put("recentPlayGameVO",new JSONObject().put("gameList",games)));}
  else if(op.equals("consult")&&method.contains("floatingball")){assert !mutation&&args.optString("source").equals("source\"channel");JSONObject pass=new JSONObject(args.optString("passThrough"));assert pass.optString("sceneId").equals("scene\"id")&&pass.optString("taskId").equals("channel-task");consultCount++;if(channelMode.equals("consultFail"))return "garbage";Object seconds=channelMode.equals("fraction")?30.1:30;if(channelMode.equals("timeType"))seconds="30";if(channelMode.equals("huge"))seconds=300;if(channelMode.equals("timeDrift")&&consultCount>1)seconds=31;result.put("data",new JSONObject().put("floatingBallVO",new JSONObject().put("timeSeconds",seconds)));if(channelMode.equals("timeConflict"))result.put("timeSeconds",29);}
  else if(op.equals("complete")&&method.contains("floatingball")){assert mutation&&TimeUtil.waited==31000&&args.length()==2&&args.optString("sceneId").equals("scene\"id");assert new JSONObject(args.optString("passThrough")).optString("taskId").equals("channel-task");if(channelMode.equals("completeFail"))return "garbage";JSONObject task=alchemyRows().optJSONObject(0);if(effect)task.put("completedNum",1).put("finishFlag",true);if(channelMode.equals("recordDrift"))task.put("recordId","other-record");}
  else if(op.equals("submitUserPlayDurationAction")){assert mutation&&args.length()==4&&args.optString("statisticTag").isEmpty()&&args.optString("gameAppId").equals("dynamic-game")&&args.optString("source").equals("source\"channel");int seconds=args.optInt("playTime");assert seconds>0&&TimeUtil.waited>=seconds*1000L;JSONObject r=alchemyRows().optJSONObject(0);if(durationMode.equals("direct"))r.put("completedNum",1).put("finishFlag",true);if(durationMode.equals("fail"))return "garbage";if(durationMode.equals("sourceDrift"))r.put("source","changed");if(durationMode.equals("recordDrift"))r.put("recordId","changed");}
  else if(op.equals("taskFeedback")){assert mutation&&(args.optString("sceneCode").equals("alchemy")&&args.optString("version").equals("alchemy")||args.optString("sceneCode").equals("zml")&&args.optString("version").equals("new"))&&args.optString("actionType").equals("TO_COMPLETE")&&args.optString("bizType").equals("LIFE_RECORD");alcFind(args.optString("templateId"));}
  else if(op.equals("pushActivity")){assert mutation&&TimeUtil.waited>=15000;JSONObject r=alcFind(args.optString("recordId"));if(effect){r.put("completedNum",r.optInt("completedNum")+1).put("finishFlag",true);if(r.optBoolean("jumpToPushModel")&&treeDelegateEffect)for(int i=0;i<rent.optJSONArray("taskDetailList").length();i++)rent.optJSONArray("taskDetailList").optJSONObject(i).put("taskProcessStatus","TO_RECEIVE");}}
  else if(op.equals("adRewardLjcs")){assert mutation;assert args.optString("adTaskBizId").equals("reward-id");}
  else if(op.equals("query")&&method.contains("applayer")){assert args.optString("spaceCode").contains("_duration=");}
  else if(op.equals("finish")&&args.optString("bizId").equals("tree-ad")){assert mutation&&args.optString("bizId").equals("tree-ad")&&TimeUtil.waited>=10000;JSONArray rows=rent.optJSONArray("spaceResultList").optJSONObject(0).optJSONArray("spaceObjectList");if(effect){if(treeAdReadback.equals("retained")){}else if(treeAdReadback.equals("unqualified")){rows.optJSONObject(0).optJSONObject("content").optJSONObject("logExtMap").put("spaceCode","no-duration");}else rows.remove(0);home.put("purificationScore",home.optInt("purificationScore")+7);}}
  else if(op.equals("finish")){assert mutation;JSONObject r=alcFind(args.optString("bizId"));assert TimeUtil.waited>=(r.optString("rewardType").equals("LJCS")?5000:10000);if(r.optJSONObject("logExtMap").optString("spaceCode").isEmpty())assert args.length()==1&&TimeUtil.waited>=15000;else assert args.optJSONObject("extendInfo")!=null;if(effect)r.put("completedNum",r.optInt("completedNum")+1).put("finishFlag",true);}
  else if(op.equals("queryTask"))result.put("data",new JSONObject().put("timeLimitedTaskVO",copy(time)));
  else if(op.equals("completeTask")){assert mutation&&args.opt("templateId").equals(time.opt("templateId"));result.put("data",new JSONObject().put("zmlNum",time.opt("rewardAmount")));if(effect)time.put("state",timeState);}
  else if(op.equals("queryEntryList")){assert args.optString("version").equals("2025-10-22");result.put("data",new JSONObject().put("entryList",new JSONArray().put(new JSONObject().put("entryCode","ALCHEMY_STAGE_REWARD").put("nextDayAwardDTO",copy(award)))));}
  else if(op.equals("claimAward")){assert mutation&&args.opt("awardId").equals(award.opt("awardId"));if(effect)award.put("awardAvailable",false);}
  else throw new AssertionError(method);
  if(mutation){if(!ack)result.put("success",false);if(cancelAfter)TimeUtil.cancel=true;if(uidAfter)io.github.aw1y2z.sesame.util.idMap.UserIdMap.uid="B";}
  if(bad.equals("falseSuccess"))result.put("success","true");if(bad.equals("fractionCode"))result.put("resultCode",200.1);if(bad.equals("nestedFailure"))result.put("data",new JSONObject().put("success",false));
  if(mutation&&effect&&!resultDrift.isEmpty()&&(op.equals("pushActivity")||op.equals("finish"))){JSONObject target=alcFind(args.optString(op.equals("pushActivity")?"recordId":"bizId"));if(resultDrift.equals("record"))target.put("recordId","other-record");else if(resultDrift.equals("template"))target.put("templateId","other-template");else if(resultDrift.equals("owner"))target.put("userId","B");}
  return nested?new JSONObject().put("resData",result).toString():result.toString();
 }
 static long countEvents(){return calls.stream().filter("submitEvent"::equals).count();}
}'''
}

test = r'''
package io.github.aw1y2z.sesame.model.task.goldenbeans;
import java.util.*;import java.net.*;import java.io.*;import org.json.*;import io.github.aw1y2z.sesame.hook.ApplicationHook;
import io.github.aw1y2z.sesame.util.*;import io.github.aw1y2z.sesame.util.idMap.UserIdMap;import io.github.aw1y2z.sesame.data.RuntimeInfo;
public class SesameCheck {
 public static class SDK extends HttpURLConnection {
  static int login,reports,opened,closed,status=200;static boolean concurrentToken;static java.util.concurrent.CyclicBarrier tokenBarrier;static boolean fail,malformed,progress,secretError,oversized;static String interrupt="";
  static final java.util.List<JSONObject> bodies=new ArrayList<>();final ByteArrayOutputStream body=new ByteArrayOutputStream();boolean ended;
  SDK(URL u){super(u);opened++;if(interrupt.equals("openUid"))UserIdMap.uid="B";if(interrupt.equals("openCancel"))TimeUtil.cancel=true;if(concurrentToken&&u.getPath().equals("/v2/zfb/taskReport")&&getThreadReports()==0){try{tokenBarrier.await(5,java.util.concurrent.TimeUnit.SECONDS);}catch(Exception e){throw new AssertionError(e);}}}static final ThreadLocal<Integer> threadReports=ThreadLocal.withInitial(()->0);static int getThreadReports(){return threadReports.get();}
  public static void auth(){if(interrupt.equals("authUid"))UserIdMap.uid="B";if(interrupt.equals("authCancel"))TimeUtil.cancel=true;}
  static void reset(){concurrentToken=false;tokenBarrier=null;threadReports.remove();login=reports=opened=closed=0;status=200;fail=malformed=progress=secretError=oversized=false;interrupt="";bodies.clear();io.github.aw1y2z.sesame.hook.AuthCodeHelper.code="auth-code";}
  public void connect(){}public void disconnect(){ended=true;closed++;}public boolean usingProxy(){return false;}public OutputStream getOutputStream(){assert UserIdMap.uid.equals("A")&&!TimeUtil.cancel;return body;}
  public int getResponseCode(){assert !getInstanceFollowRedirects();assert getConnectTimeout()==10000&&getReadTimeout()==15000;assert getRequestMethod().equals("POST");assert !io.github.aw1y2z.sesame.data.task.TaskLifecycle.isIdle()&&io.github.aw1y2z.sesame.data.task.TaskLifecycle.freezeIfIdle()==null;return status;}
  public InputStream getInputStream() throws IOException {if(secretError)throw new IOException("server-secret-123");JSONObject j=new JSONObject(body.toString(java.nio.charset.StandardCharsets.UTF_8));synchronized(bodies){bodies.add(j);}assert j.optString("gid").startsWith("zfb_")&&!j.has("score")&&!j.has("playTime");JSONObject response=new JSONObject().put("code",fail?0:1).put("serverMessage","server-secret-123");
   if(url.getPath().equals("/v2/game/login")){login++;assert j.optString("code").equals("auth-code");response.put("data",new JSONObject().put("token",concurrentToken?"sdk-token-"+Thread.currentThread().getName():"sdk-token"));if(interrupt.equals("loginUid"))UserIdMap.uid="B";if(interrupt.equals("loginCancel"))TimeUtil.cancel=true;}
   else{assert url.getPath().equals("/v2/zfb/taskReport");reports++;threadReports.set(getThreadReports()+1);assert getRequestProperty("authorization").equals(concurrentToken?"sdk-token-"+Thread.currentThread().getName():"sdk-token")&&j.optString("action_finish_channel").length()>0&&j.optString("action_code").length()>0;if(interrupt.equals("reportUid"))UserIdMap.uid="B";if(interrupt.equals("reportCancel"))TimeUtil.cancel=true;if(progress&&ApplicationHook.alchemyRows().length()>0)ApplicationHook.alchemyRows().optJSONObject(0).put("completedNum",1).put("finishFlag",true);}
   return new ByteArrayInputStream((oversized?"X".repeat(70000):malformed?"garbage":response.toString()).getBytes(java.nio.charset.StandardCharsets.UTF_8)){public synchronized int read(byte[] target,int off,int length){int n=super.read(target,off,length);if(interrupt.equals("readUid"))UserIdMap.uid="B";if(interrupt.equals("readCancel"))TimeUtil.cancel=true;return n;}};}
 }

 static void reset(){Log.messages.clear();ApplicationHook.resultDrift="";ApplicationHook.creditQueries=0;ApplicationHook.treeDelegateEffect=true;ApplicationHook.delegateDrift=false;SDK.reset();Thread.interrupted();UserIdMap.uid="A";TimeUtil.cancel=false;TimeUtil.waited=0;TimeUtil.interruptAt=0;TimeUtil.interrupt="";MyUtils.offset=0;RuntimeInfo.users.clear();RuntimeInfo.writable=true;Log.confirmed=0;ApplicationHook.mutations=ApplicationHook.queries=0;ApplicationHook.calls.clear();ApplicationHook.effect=ApplicationHook.ack=ApplicationHook.readback=true;ApplicationHook.nested=ApplicationHook.drift=ApplicationHook.uidAfter=ApplicationHook.cancelAfter=false;ApplicationHook.bad=ApplicationHook.failOp=ApplicationHook.treeAdReadback="";ApplicationHook.timeState=2;
  ApplicationHook.home=new JSONObject().put("browseTaskList",new JSONArray()).put("taskStatusList",new JSONArray()).put("staticSceneGuideTaskList",new JSONArray()).put("purificationScore",0).put("trees",new JSONArray().put(new JSONObject().put("treeCode","server-tree").put("remainPurificationClickNum",0))).put("garbageMap",new JSONObject().put("type",new JSONArray()));
  ApplicationHook.p2eMode="";ApplicationHook.p2eSeconds=90;ApplicationHook.reported=0;ApplicationHook.chunks.clear();ApplicationHook.durationMode=ApplicationHook.channelMode="";ApplicationHook.consultCount=0;ApplicationHook.credit=new JSONObject().put("toCompleteVOS",new JSONArray());ApplicationHook.rent=new JSONObject().put("taskDetailList",new JSONArray());ApplicationHook.alchemy=new JSONObject().put("toCompleteVOS",new JSONArray()).put("dailyTaskListVO",new JSONObject().put("waitJoinTaskVOS",new JSONArray()).put("waitCompleteTaskVOS",new JSONArray()));
  ApplicationHook.time=new JSONObject().put("templateId","time\"id").put("state",1).put("tomorrow",false).put("rewardAmount",3);
  ApplicationHook.award=new JSONObject().put("awardId","award\"id").put("awardAvailable",true).put("pointValue",6);
 }
 static JSONObject tree(String id,String status){return new JSONObject().put("taskBaseInfo",new JSONObject().put("appletId",id).put("title","浏览页面")).put("taskProcessStatus",status).put("needSignUp",true).put("needManuallyReceiveAward",true).put("chInfo","context\"channel").put("refer","context-refer").put("playInfo","context-play");}
 static JSONObject alc(String id){return new JSONObject().put("templateId",id).put("recordId","").put("title","浏览芝麻页面").put("bizType","LIFE_RECORD").put("completedNum",0).put("needCompleteNum",1).put("finishFlag",false).put("shareAssist",false);}
 static JSONObject duration(){JSONObject task=alc("duration-game").put("recordId","duration-record").put("title","game").put("gameAppId","dynamic-game").put("gameTaskType","shichang").put("source","source\"channel").put("playTime",31);ApplicationHook.alchemyRows().put(task);return task;}
 static JSONObject channel(){JSONObject task=alc("channel-game").put("recordId","channel-record").put("title","game").put("actionUrl","alipays://platformapi/startapp?taskType=durationTask&sceneId=scene%22id&taskId=channel-task&source=source%22channel&moduleId=module-id&guideType=guide-id");ApplicationHook.alchemyRows().put(task);return task;}
 static JSONObject p2e(){JSONObject pages=new JSONObject();for(String kind:new String[]{"HomePage","TaskList","FeedsGameList"})pages.put("p2e"+kind+"Request",new JSONObject().put("source","p2e\"source").put("opaque","query"+kind).put("zero",0).put("unknown",new JSONArray().put(new JSONObject().put("preserve",true))));JSONObject task=alc("p2e-template").put("recordId","p2e-record").put("title","game").put("sceneId","entry-scene").put("taskId","p2e-task").put("moduleId","entry-module").put("guideType","guide").put("source","p2e\"source").put("oriChInfo","ori\"channel").put("trafficDriverId","p2e-driver").put("componentChannel","p2e-channel").put("componentScene","p2e-scene").put("floatingBallTypeList",new JSONArray().put("P2E_GAME_BROWSE_TASK_FLOATING_BALL")).put("p2ePageRequests",pages);ApplicationHook.alchemyRows().put(task);return task;}
 static void run(String domain){SesameCreditExtras.run(domain.equals("treeTasks"),domain.equals("treeClean"),domain.equals("alchemyTasks"),domain.equals("alchemyTime"),domain.equals("alchemyNextDay"));}
 static long count(String op){return ApplicationHook.calls.stream().filter(op::equals).count();}
 static void unknown(String domain){assert !RuntimeInfo.getInstance().getString("golden::sesameExtra::"+domain+"::unknown").isEmpty():domain;int n=ApplicationHook.calls.size();run(domain);assert n==ApplicationHook.calls.size();}
 static void prepare(String domain){switch(domain){case "treeTasks"->ApplicationHook.rows().put(tree("tree\"id","NOT_DONE"));case "treeClean"->{ApplicationHook.home.put("purificationScore",100);ApplicationHook.home.optJSONArray("trees").optJSONObject(0).put("remainPurificationClickNum",1);ApplicationHook.home.optJSONObject("garbageMap").optJSONArray("type").put(new JSONObject().put("subType","server-area"));}case "alchemyTasks"->ApplicationHook.alchemyRows().put(alc("alc\"id").put("recordId","existing\"record"));}}
 static JSONObject delegate(){ApplicationHook.rent.optJSONArray("taskDetailList").put(tree("rent-delegate","NOT_DONE").put("taskChannel","RENT").put("taskBaseInfo",new JSONObject().put("appletId","rent-delegate").put("appletType","PUSH_MODEL").put("title","\u6d4f\u89c8\u9875\u9762").put("appId","dynamic-app")));JSONObject record=alc("zml_zmzl_cyz_erfang").put("title","\u6d4f\u89c8\u829d\u9ebb\u79df\u8d41").put("recordId","delegate-record").put("jumpToPushModel",true).put("strategyRule",new JSONObject().put("merchantName","\u829d\u9ebb\u79df\u8d41")).put("actionUrl","alipays://platformapi/startapp?appId=dynamic-app").put("appId","dynamic-app");ApplicationHook.credit.optJSONArray("toCompleteVOS").put(record);return record;}
 public static void main(String[] args){
  for(int seconds:new int[]{1,16,45,300}){reset();ApplicationHook.rows().put(tree("timed","NOT_DONE").put("taskMaterial",new JSONObject().put("taskType","BROWSER").put("browseTime",seconds).put("jumpUrl","https://example.invalid/browser")));run("treeTasks");assert count("RENT_GREEN_TASK_FINISH")==2&&Log.confirmed==2&&TimeUtil.waited==seconds*1000L:seconds;}
  for(Object seconds:new Object[]{0,301,-1,1.5,"45",JSONObject.NULL}){reset();ApplicationHook.rows().put(tree("timed","NONE_SIGNUP").put("taskMaterial",new JSONObject().put("taskType","BROWSER").put("browseTime",seconds).put("jumpUrl","https://example.invalid/browser")));run("treeTasks");assert ApplicationHook.mutations==0&&TimeUtil.waited==0:seconds;}
  reset();ApplicationHook.rows().put(tree("timed","NONE_SIGNUP").put("taskMaterial",new JSONObject().put("taskType","BROWSER").put("browseTime",45).put("jumpUrl","https://example.invalid/browser")));run("treeTasks");assert count("RENT_GREEN_TASK_FINISH")==3&&Log.confirmed==3&&TimeUtil.waited==45000;
  reset();ApplicationHook.rows().put(tree("sign","NOT_DONE").put("taskMaterial",new JSONObject().put("taskType","CONTINUE_SIGN_TASK")));run("treeTasks");assert ApplicationHook.mutations==2&&TimeUtil.waited==0;
  for(String type:new String[]{"ORDER","COMP_TRANS","DIVERSION","SHARE","SUBSCRIPTION","SET_HOME","ZMT_ORDER","REPEAT_VISIT_TASK","UNKNOWN"}){reset();ApplicationHook.rows().put(tree("unsafe","NONE_SIGNUP").put("taskMaterial",new JSONObject().put("taskType",type).put("browseTime",45).put("jumpUrl","https://example.invalid/browser")));run("treeTasks");assert ApplicationHook.mutations==0&&TimeUtil.waited==0:type;}
  for(String stop:new String[]{"uid","cancel","day"}){reset();ApplicationHook.rows().put(tree("timed","NOT_DONE").put("taskMaterial",new JSONObject().put("taskType","BROWSER").put("browseTime",45).put("jumpUrl","https://example.invalid/browser")));TimeUtil.interruptAt=3000;TimeUtil.interrupt=stop;try{run("treeTasks");assert stop.equals("day");}catch(TaskCancelledException expected){assert !stop.equals("day");}assert ApplicationHook.mutations==0&&RuntimeInfo.getInstance().getString("golden::sesameExtra::treeTasks::unknown").isEmpty();}
  for(String field:new String[]{"taskType","browseTime","jumpUrl"}){reset();JSONObject row=tree("timed","NOT_DONE").put("taskMaterial",new JSONObject().put("taskType","BROWSER").put("browseTime",45).put("jumpUrl","https://example.invalid/browser"));ApplicationHook.rows().put(row);TimeUtil.interruptAt=3000;TimeUtil.interrupt="durationDrift";TimeUtil.drift=()->row.optJSONObject("taskMaterial").put(field,field.equals("browseTime")?46:"changed");run("treeTasks");assert ApplicationHook.mutations==0:field;}
  for(String missing:new String[]{"browseTime","jumpUrl"}){reset();JSONObject material=new JSONObject().put("taskType","BROWSER").put("browseTime",45).put("jumpUrl","https://example.invalid/browser");material.remove(missing);ApplicationHook.rows().put(tree("timed","NOT_DONE").put("taskMaterial",material));run("treeTasks");assert ApplicationHook.mutations==0:missing;}
  URL.setURLStreamHandlerFactory(protocol->protocol.equals("https")?new URLStreamHandler(){protected URLConnection openConnection(URL u){assert u.getHost().equals("gamesapi2.aslk2018.com");return new SDK(u);}}:null);
  for(String app:new String[]{"2060170000356601","2021004149679303","2060170000363691","2021005113684028"}){reset();io.github.aw1y2z.sesame.model.task.antGame.GameTask game=io.github.aw1y2z.sesame.model.task.antGame.GameTask.matchAppId(app);int submitted=game.reportSync("source sdk",1);assert SDK.login==1&&SDK.reports==submitted&&submitted>0&&io.github.aw1y2z.sesame.data.task.TaskLifecycle.isIdle();}
  reset();SDK.concurrentToken=true;SDK.tokenBarrier=new java.util.concurrent.CyclicBarrier(2);java.util.concurrent.atomic.AtomicReference<Throwable> concurrentError=new java.util.concurrent.atomic.AtomicReference<>();Runnable sdkRun=()->{try{assert io.github.aw1y2z.sesame.model.task.antGame.GameTask.Orchard_ncscc.reportSync("concurrent source sdk",1)==2;}catch(Throwable error){concurrentError.set(error);}};Thread sdkA=new Thread(sdkRun,"first"),sdkB=new Thread(sdkRun,"second");sdkA.start();sdkB.start();try{sdkA.join(10000);sdkB.join(10000);}catch(InterruptedException e){throw new AssertionError(e);}assert !sdkA.isAlive()&&!sdkB.isAlive()&&concurrentError.get()==null:concurrentError.get();assert io.github.aw1y2z.sesame.data.task.TaskLifecycle.isIdle();
  for(String stop:new String[]{"authUid","authCancel","openUid","openCancel","readUid","readCancel","loginUid","loginCancel","reportUid","reportCancel"}){reset();SDK.interrupt=stop;try{io.github.aw1y2z.sesame.model.task.antGame.GameTask.Orchard_ncscc.reportSync("source sdk",1);throw new AssertionError(stop);}catch(TaskCancelledException expected){}assert SDK.opened==SDK.closed&&SDK.reports==(stop.startsWith("report")?1:0)&&io.github.aw1y2z.sesame.data.task.TaskLifecycle.isIdle():stop;}
  for(String bad:new String[]{"noAuth","fail","malformed","redirect","http500","secretError","oversized"}){reset();switch(bad){case "noAuth"->io.github.aw1y2z.sesame.hook.AuthCodeHelper.code="";case "fail"->SDK.fail=true;case "malformed"->SDK.malformed=true;case "redirect"->SDK.status=302;case "http500"->SDK.status=500;case "secretError"->SDK.secretError=true;case "oversized"->SDK.oversized=true;}assert io.github.aw1y2z.sesame.model.task.antGame.GameTask.Orchard_ncscc.reportSync("source sdk",1)==0&&SDK.opened==SDK.closed&&SDK.reports==0:bad;assert Log.messages.stream().noneMatch(m->m.contains("server-secret-123")||m.contains("sdk-token")):Log.messages;}
  reset();assert io.github.aw1y2z.sesame.model.task.antGame.GameTask.Orchard_ncscc.reportSync("source sdk",1001)==0&&SDK.opened==0;io.github.aw1y2z.sesame.data.task.TaskLifecycle.Freeze frozen=io.github.aw1y2z.sesame.data.task.TaskLifecycle.freezeIfIdle();try{io.github.aw1y2z.sesame.model.task.antGame.GameTask.Orchard_ncscc.reportSync("source sdk",1);throw new AssertionError();}catch(TaskCancelledException expected){}assert SDK.opened==0;io.github.aw1y2z.sesame.data.task.TaskLifecycle.thaw(frozen);
  for(String app:new String[]{"2060170000356601","2021004149679303","2060170000363691","2021005113684028"})for(boolean direct:new boolean[]{false,true}){reset();SDK.progress=direct;ApplicationHook.alchemyRows().put(alc("game-template").put("title","game").put("gameAppId",app).put("recordId","game-record"));run("alchemyTasks");assert SDK.login==1&&SDK.reports>0&&Log.confirmed==1&&count("pushActivity")== (direct?0:1):SDK.login+"/"+SDK.reports+"/"+Log.confirmed+"/"+ApplicationHook.calls;int reports=SDK.reports;run("alchemyTasks");assert SDK.reports==reports;}
  for(String failure:new String[]{"ackOnly","sdkFail","p2e","duration","appidDrift","owner","unsafe"}){reset();JSONObject game=alc("game-template").put("title","game").put("gameAppId","2060170000356601").put("recordId","game-record");ApplicationHook.alchemyRows().put(game);switch(failure){case "ackOnly"->ApplicationHook.effect=false;case "sdkFail"->SDK.fail=true;case "p2e"->game.put("p2eTask",true);case "duration"->game.put("playTime",10);case "appidDrift"->game.put("appId","2021004149679303");case "owner"->game.put("userId","B");case "unsafe"->game.put("title","\u8d2d\u4e70\u6e38\u620f\u670d\u52a1");}run("alchemyTasks");assert Log.confirmed==0:failure;if(failure.equals("ackOnly")||failure.equals("sdkFail")){assert SDK.login==1;unknown("alchemyTasks");}else assert SDK.opened==0&&ApplicationHook.mutations==0;}
  for(boolean direct:new boolean[]{false,true}){reset();duration();ApplicationHook.durationMode=direct?"direct":"";run("alchemyTasks");assert count("submitUserPlayDurationAction")==1&&count("pushActivity")== (direct?0:1)&&Log.confirmed==1&&SDK.opened==0&&TimeUtil.waited==(direct?31000:46000);run("alchemyTasks");assert count("submitUserPlayDurationAction")==1;}
  for(String key:new String[]{"timeCount","floatBallDuration","requiredDuration","duration","vstTime"}){reset();JSONObject task=duration();task.remove("playTime");task.put(key,key.equals("vstTime")?30000:31);run("alchemyTasks");assert count("submitUserPlayDurationAction")==1&&TimeUtil.waited==46000:key;}
  reset();JSONObject flat=duration();flat.remove("gameTaskType");run("alchemyTasks");assert count("submitUserPlayDurationAction")==1;
  reset();flat=duration();flat.remove("gameAppId");flat.put("appId","dynamic-game");run("alchemyTasks");assert count("submitUserPlayDurationAction")==1;
  reset();flat=duration();flat.put("recordId","");run("alchemyTasks");assert count("joinActivity")==1&&count("submitUserPlayDurationAction")==1&&Log.confirmed==2;
  for(String bad:new String[]{"missingSource","sourceType","missingApp","missingTime","zero","fraction","timeType","huge","conflict","appidConflict","kind","kindType","p2e","page","float","logFloat","unsafe","assist","owner","needPlayTime"}){reset();JSONObject task=duration();switch(bad){case "missingSource"->task.remove("source");case "sourceType"->task.put("source",123);case "missingApp"->task.remove("gameAppId");case "missingTime"->task.remove("playTime");case "zero"->task.put("playTime",0);case "fraction"->task.put("playTime",31.1);case "timeType"->task.put("playTime","31");case "huge"->task.put("playTime",301);case "conflict"->task.put("duration",30);case "appidConflict"->task.put("appId","different");case "kind"->task.put("gameTaskType","score");case "kindType"->task.put("gameTaskType",true);case "p2e"->task.put("p2eTask",true);case "page"->task.put("p2ePageRequests",new JSONObject());case "float"->task.put("floatingBallTypeList",new JSONArray().put("P2E_GAME_BROWSE_TASK_FLOATING_BALL"));case "logFloat"->task.put("logExtMap",new JSONObject().put("passThrough","opaque"));case "unsafe"->task.put("title","\u8d2d\u4e70\u6e38\u620f\u670d\u52a1");case "assist"->task.put("shareAssist",true);case "owner"->task.put("userId","B");case "needPlayTime"->task.put("needPlayTime",10);}run("alchemyTasks");assert ApplicationHook.mutations==0&&SDK.opened==0:bad;}
  for(String mode:new String[]{"fail","sourceDrift","recordDrift","ackOnly"}){reset();duration();ApplicationHook.durationMode=mode;if(mode.equals("ackOnly"))ApplicationHook.effect=false;run("alchemyTasks");assert count("submitUserPlayDurationAction")==1&&Log.confirmed==0:mode;unknown("alchemyTasks");MyUtils.offset=1;unknown("alchemyTasks");}
  for(String stop:new String[]{"uid","cancel","day","durationDrift"}){reset();duration();TimeUtil.drift=()->ApplicationHook.alchemyRows().optJSONObject(0).put("playTime",32);TimeUtil.interruptAt=3000;TimeUtil.interrupt=stop;try{run("alchemyTasks");assert stop.equals("day")||stop.equals("durationDrift");}catch(TaskCancelledException expected){assert stop.equals("uid")||stop.equals("cancel");}assert count("submitUserPlayDurationAction")==0&&count("pushActivity")==0:stop;UserIdMap.uid="A";TimeUtil.cancel=false;unknown("alchemyTasks");}
  reset();channel();run("alchemyTasks");assert count("taskFeedback")==1&&count("queryHomePage")==1&&count("submitUserPlayDurationAction")==1&&count("complete")==1&&count("pushActivity")==0&&Log.confirmed==1&&TimeUtil.waited==31000&&SDK.opened==0;run("alchemyTasks");assert count("complete")==1;
  reset();JSONObject channel=channel();channel.put("recordId","");run("alchemyTasks");assert count("joinActivity")==1&&count("complete")==1&&Log.confirmed==2;
  for(String bad:new String[]{"missingScene","missingTask","missingModule","missingGuide","missingSource","duplicate","conflict","type","p2e","p2eUrl","logP2e","unsafe","assist","owner"}){reset();JSONObject task=channel();String url=task.optString("actionUrl");switch(bad){case "missingScene"->url=url.replace("&sceneId=scene%22id","");case "missingTask"->url=url.replace("&taskId=channel-task","");case "missingModule"->url=url.replace("&moduleId=module-id","");case "missingGuide"->url=url.replace("&guideType=guide-id","");case "missingSource"->url=url.replace("&source=source%22channel","");case "duplicate"->url+="&sceneId=other";case "conflict"->task.put("sceneId","other");case "type"->task.put("sceneId",12);case "p2e"->task.put("p2eTask",true);case "p2eUrl"->url+="&floatingBallTypeList=P2E_GAME_BROWSE_TASK_FLOATING_BALL";case "logP2e"->task.put("logExtMap",new JSONObject().put("p2ePageRequests",new JSONObject()));case "unsafe"->task.put("title","\u8d2d\u4e70\u6e38\u620f");case "assist"->task.put("shareAssist",true);case "owner"->task.put("userId","B");}task.put("actionUrl",url);run("alchemyTasks");assert ApplicationHook.mutations==0&&SDK.opened==0:bad;}
  for(String mode:new String[]{"homeFail","noGame","gameDrift","consultFail","fraction","timeType","huge","timeConflict","timeDrift","completeFail","recordDrift","ackOnly"}){reset();channel();ApplicationHook.channelMode=mode;if(mode.equals("ackOnly"))ApplicationHook.effect=false;run("alchemyTasks");assert Log.confirmed==0:mode;unknown("alchemyTasks");MyUtils.offset=1;unknown("alchemyTasks");assert SDK.opened==0&&count("pushActivity")==0;}
  for(String stop:new String[]{"uid","cancel","day"}){reset();channel();TimeUtil.interruptAt=3000;TimeUtil.interrupt=stop;try{run("alchemyTasks");assert stop.equals("day");}catch(TaskCancelledException expected){assert !stop.equals("day");}assert count("submitUserPlayDurationAction")==0&&count("complete")==0;UserIdMap.uid="A";TimeUtil.cancel=false;unknown("alchemyTasks");}

  for(int seconds:new int[]{1,30,31,90,299}){reset();p2e();ApplicationHook.p2eSeconds=seconds;run("alchemyTasks");assert count("gameP2eFloatingBallComplete")==1&&ApplicationHook.reported==seconds+1&&Log.confirmed==1&&TimeUtil.waited==(seconds+1)*1000L&&SDK.opened==0&&count("pushActivity")==0:ApplicationHook.calls;int writes=ApplicationHook.mutations;run("alchemyTasks");assert ApplicationHook.mutations==writes;}
  reset();p2e();run("alchemyTasks");assert ApplicationHook.chunks.equals(List.of(31,30,30))&&count("submitEvent")==2&&count("queryGameComponent")==2;
  assert ApplicationHook.calls.indexOf("taskFeedback")<ApplicationHook.calls.indexOf("submitEvent")&&ApplicationHook.calls.indexOf("submitUserAction")<ApplicationHook.calls.indexOf("gameP2eFloatingBallConsult")&&ApplicationHook.calls.indexOf("submitUserPlayDurationAction")<ApplicationHook.calls.indexOf("gameP2eFloatingBallComplete");
  for(String form:new String[]{"encoded","aliases","nested","url","explicit","join","wrapped","blank","chInfo","query","entryFallback"}){reset();JSONObject task=p2e();JSONObject pages=task.optJSONObject("p2ePageRequests");switch(form){case "encoded"->{task.put("p2ePageRequests",pages.toString());task.put("floatingBallTypeList",task.optJSONArray("floatingBallTypeList").toString());}case "aliases"->{for(String kind:new String[]{"HomePage","TaskList","FeedsGameList"})pages.put("query"+kind+"Request",pages.remove("p2e"+kind+"Request"));task.put("p2eComponentChannel",task.remove("componentChannel"));task.put("gameScene",task.remove("componentScene"));}case "nested"->{JSONObject metadata=new JSONObject();for(String key:new String[]{"sceneId","taskId","moduleId","guideType","source","oriChInfo","trafficDriverId","componentChannel","componentScene","floatingBallTypeList","p2ePageRequests"})metadata.put(key,task.remove(key));task.put("extend",new JSONObject().put("floatBallConfig",metadata.toString()));}case "url"->{JSONObject pass=new JSONObject();for(String key:new String[]{"sceneId","taskId","moduleId","guideType","source","oriChInfo","trafficDriverId","componentChannel","componentScene","floatingBallTypeList"})pass.put(key,task.remove(key));task.put("actionUrl","alipays://start?channelTaskPassThrough="+java.net.URLEncoder.encode(pass.toString(),java.nio.charset.StandardCharsets.UTF_8));}case "explicit"->task.put("gameAppId","p2e-app").put("gameId","p2e-game").put("gameModuleId","p2e-module").put("gameVersion","v1");case "join"->task.put("recordId","");case "wrapped"->ApplicationHook.nested=true;case "blank"->task.put("gameAppId","").put("gameVersion","");case "chInfo"->task.put("chInfo",task.remove("source"));case "query"->{StringJoiner query=new StringJoiner("&");for(String key:new String[]{"sceneId","taskId","moduleId","guideType","source","oriChInfo","trafficDriverId","componentChannel","componentScene","floatingBallTypeList"})query.add(key+"="+java.net.URLEncoder.encode(String.valueOf(task.remove(key)),java.nio.charset.StandardCharsets.UTF_8));task.put("actionUrl","alipays://start?query="+java.net.URLEncoder.encode(query.toString(),java.nio.charset.StandardCharsets.UTF_8));}case "entryFallback"->{ApplicationHook.p2eMode=form;task.put("gameModuleId","p2e-module").put("gameVersion","v1");}}run("alchemyTasks");assert count("gameP2eFloatingBallComplete")==1&&Log.confirmed==(form.equals("join")?2:1):form+ApplicationHook.calls;}
  for(String bad:new String[]{"missingRequest","requestSource","requestType","requestOwner","requestConflict","missingField","fieldType","fieldConflict","typeList","duplicateType","malformed","unsafe","assist","owner","tooMany"}){reset();JSONObject task=p2e();JSONObject pages=task.optJSONObject("p2ePageRequests"),home=pages.optJSONObject("p2eHomePageRequest");switch(bad){case "missingRequest"->pages.remove("p2eTaskListRequest");case "requestSource"->home.put("source","other");case "requestType"->pages.put("p2eHomePageRequest",true);case "requestOwner"->home.put("userId","B");case "requestConflict"->pages.put("queryHomePageRequest",new JSONObject(home.toString()).put("zero",1));case "missingField"->task.remove("trafficDriverId");case "fieldType"->task.put("taskId",123);case "fieldConflict"->task.put("extend",new JSONObject().put("taskId","other"));case "typeList"->task.put("floatingBallTypeList",new JSONArray().put("UNKNOWN"));case "duplicateType"->task.optJSONArray("floatingBallTypeList").put("P2E_GAME_BROWSE_TASK_FLOATING_BALL");case "malformed"->task.put("extend","garbage");case "unsafe"->task.put("title","\u8d2d\u4e70\u6e38\u620f");case "assist"->task.put("shareAssist",true);case "owner"->task.put("userId","B");case "tooMany"->{for(int i=0;i<129;i++)home.put("extra"+i,i);}}run("alchemyTasks");assert ApplicationHook.mutations==0&&SDK.opened==0:bad;}
  for(String mode:new String[]{"noGame","ambiguous","incomplete","owner"}){reset();p2e();ApplicationHook.p2eMode=mode;run("alchemyTasks");assert ApplicationHook.mutations==0&&Log.confirmed==0&&SDK.opened==0:mode;}
  for(String mode:new String[]{"initFail","loadingFail","timeType","fraction","timeDrift","typeDrift","consultAck","durationFail","chunk2Fail","durationAck","gameDrift","versionDrift","completeFail","completeAck","recordDrift","ackOnly"}){reset();p2e();ApplicationHook.p2eMode=mode;if(mode.equals("ackOnly"))ApplicationHook.effect=false;run("alchemyTasks");assert Log.confirmed==0&&count("pushActivity")==0&&SDK.opened==0:mode;unknown("alchemyTasks");MyUtils.offset=1;unknown("alchemyTasks");if(mode.equals("chunk2Fail"))assert ApplicationHook.chunks.equals(List.of(31,30));if(List.of("gameDrift","versionDrift","timeDrift").contains(mode))assert count("submitUserPlayDurationAction")==0:mode;}
  for(int seconds:new int[]{0,300}){reset();p2e();ApplicationHook.p2eSeconds=seconds;run("alchemyTasks");assert count("submitUserPlayDurationAction")==0&&count("gameP2eFloatingBallComplete")==0;unknown("alchemyTasks");}
  for(String stop:new String[]{"uid","cancel","day","requestDrift","recordDrift"}){reset();JSONObject task=p2e();TimeUtil.drift=()->{if(stop.equals("requestDrift"))task.optJSONObject("p2ePageRequests").optJSONObject("p2eHomePageRequest").put("zero",1);else task.put("recordId","different");};TimeUtil.interruptAt=32000;TimeUtil.interrupt=stop.endsWith("Drift")?"durationDrift":stop;try{run("alchemyTasks");assert List.of("day","requestDrift","recordDrift").contains(stop);}catch(TaskCancelledException expected){assert stop.equals("uid")||stop.equals("cancel");}assert count("submitUserPlayDurationAction")==1&&count("gameP2eFloatingBallComplete")==0:stop;UserIdMap.uid="A";TimeUtil.cancel=false;unknown("alchemyTasks");}
  reset();p2e();RuntimeInfo.writable=false;run("alchemyTasks");assert ApplicationHook.mutations==0;

  reset();delegate();run("treeTasks");assert count("actionSubmit")==1&&count("pushActivity")==1&&count("RENT_GREEN_TASK_FINISH")==1&&Log.confirmed==2;int actions=ApplicationHook.mutations;run("treeTasks");assert ApplicationHook.mutations==actions;
  for(String kind:new String[]{"unmatched","missingRecord","unsafe","merchant","duplicate","drift","effect","ack","readback","treeOnly"}){reset();JSONObject record=delegate();switch(kind){case "unmatched"->record.put("appId","other-app");case "missingRecord"->record.remove("recordId");case "unsafe"->record.put("title","\u7b7e\u7ea6\u79df\u8d41");case "merchant"->record.optJSONObject("strategyRule").put("merchantName","another");case "duplicate"->ApplicationHook.credit.optJSONArray("toCompleteVOS").put(new JSONObject(record.toString()));case "drift"->ApplicationHook.delegateDrift=true;case "effect"->ApplicationHook.effect=false;case "ack"->ApplicationHook.ack=false;case "readback"->ApplicationHook.readback=false;case "treeOnly"->ApplicationHook.treeDelegateEffect=false;}run("treeTasks");assert Log.confirmed==0:kind;if(List.of("effect","ack","readback","treeOnly").contains(kind)){assert ApplicationHook.mutations>0;unknown("treeTasks");}else assert ApplicationHook.mutations==0:kind;}
  for(String stop:new String[]{"uid","cancel","day"}){reset();delegate();TimeUtil.interruptAt=3000;TimeUtil.interrupt=stop;try{run("treeTasks");assert stop.equals("day");}catch(TaskCancelledException expected){assert !stop.equals("day");}assert count("actionSubmit")==0&&count("pushActivity")==0&&ApplicationHook.mutations==1;}
  TimeZone.setDefault(TimeZone.getTimeZone("America/Los_Angeles"));reset();SesameCreditExtras.run(false,false,false,false,false);assert ApplicationHook.calls.isEmpty();
  reset();ApplicationHook.rows().put(tree("tree\"id","NONE_SIGNUP"));run("treeTasks");assert count("RENT_GREEN_TASK_FINISH")==3&&TimeUtil.waited==16000&&Log.confirmed==3;int n=ApplicationHook.mutations;run("treeTasks");assert n==ApplicationHook.mutations;
  reset();ApplicationHook.rent.optJSONArray("taskDetailList").put(tree("rent","NOT_DONE").put("taskChannel","RENT"));ApplicationHook.rent.optJSONArray("taskDetailList").optJSONObject(0).optJSONObject("taskBaseInfo").put("appId","dynamic-app");run("treeTasks");assert ApplicationHook.mutations==2;
  reset();prepare("treeClean");run("treeClean");assert ApplicationHook.mutations==1&&ApplicationHook.home.optInt("purificationScore")==0&&Log.confirmed==1;
  reset();ApplicationHook.alchemyRows().put(alc("alc\"id"));run("alchemyTasks");assert count("joinActivity")==1&&count("taskFeedback")==1&&count("pushActivity")==1&&TimeUtil.waited==15000&&Log.confirmed==2;
  reset();ApplicationHook.alchemyRows().put(alc("zml_zmzl_cyz_erfang").put("title","浏览芝麻租赁").put("recordId","rent-record"));run("alchemyTasks");assert count("actionSubmit")==1&&count("taskFeedback")==1&&count("pushActivity")==1&&Log.confirmed==1;
  reset();ApplicationHook.alchemyRows().put(alc("source-ad").put("bizType","AD_TASK").put("title","浏览广告").put("logExtMap",new JSONObject().put("bizId","source-biz")));run("alchemyTasks");assert count("finish")==1&&count("query")==0&&TimeUtil.waited==15000&&Log.confirmed==1;
  for(String reward:new String[]{"LJCS","ZML"}){reset();JSONObject ad=alc("ad").put("bizType","AD_TASK").put("title","浏览广告").put("rewardType",reward).put("adTaskBizId","reward-id").put("logExtMap",new JSONObject().put("bizId","biz\"id").put("ch","dynamic-channel").put("adPositionId","dynamic-pos").put("spaceCode","server_ad_duration=10"));ApplicationHook.alchemyRows().put(ad);run("alchemyTasks");assert count("finish")==1&&count("query")==1&&TimeUtil.waited==(reward.equals("LJCS")?5000:10000)&&count("adRewardLjcs")== (reward.equals("LJCS")?1:0)&&Log.confirmed==1;}
  for(boolean encoded:new boolean[]{false,true}){reset();JSONObject content=new JSONObject().put("title","browse ad").put("rewardNum","7").put("logExtMap",new JSONObject().put("bizId","tree-ad").put("spaceCode","server_ad_duration=10"));ApplicationHook.rent.put("spaceResultList",new JSONArray().put(new JSONObject().put("spaceObjectList",new JSONArray().put(new JSONObject().put("content",encoded?content.toString():content)))));run("treeTasks");assert ApplicationHook.mutations==1&&count("finish")==1&&TimeUtil.waited==10000&&ApplicationHook.home.optInt("purificationScore")==7&&Log.confirmed==1;}
  for(String mode:new String[]{"retained","unqualified"}){reset();JSONObject content=new JSONObject().put("title","browse ad").put("rewardNum","7").put("logExtMap",new JSONObject().put("bizId","tree-ad").put("spaceCode","server_ad_duration=10"));ApplicationHook.rent.put("spaceResultList",new JSONArray().put(new JSONObject().put("spaceObjectList",new JSONArray().put(new JSONObject().put("content",content)))));ApplicationHook.treeAdReadback=mode;run("treeTasks");assert ApplicationHook.mutations==1&&Log.confirmed==0;unknown("treeTasks");}
  for(String domain:new String[]{"alchemyTime","alchemyNextDay"}){reset();run(domain);assert ApplicationHook.mutations==1&&Log.confirmed==1;run(domain);assert ApplicationHook.mutations==1;}
  for(String domain:new String[]{"treeTasks","treeClean","alchemyTasks","alchemyTime","alchemyNextDay"})for(String failure:new String[]{"effect","ack","readback"}){reset();prepare(domain);switch(failure){case "effect"->ApplicationHook.effect=false;case "ack"->ApplicationHook.ack=false;case "readback"->ApplicationHook.readback=false;}run(domain);assert ApplicationHook.mutations>0&&Log.confirmed==0:domain+failure;unknown(domain);}
  for(String domain:new String[]{"treeTasks","treeClean","alchemyTasks","alchemyTime","alchemyNextDay"}){reset();prepare(domain);RuntimeInfo.writable=false;run(domain);assert ApplicationHook.mutations==0:domain;}
  for(String mode:new String[]{"falseSuccess","fractionCode","nestedFailure"}){reset();prepare("treeTasks");ApplicationHook.bad=mode;run("treeTasks");assert ApplicationHook.mutations==0:mode;}
  reset();prepare("treeTasks");ApplicationHook.nested=true;run("treeTasks");assert ApplicationHook.mutations==2;
  for(String kind:new String[]{"idType","statusType","manualType","signupType","duplicate","malformedMorpho","owner","event","external","push"}){reset();JSONObject t=tree("tree","NOT_DONE");ApplicationHook.rows().put(t);switch(kind){case "idType"->t.optJSONObject("taskBaseInfo").put("appletId",123);case "statusType"->t.put("taskProcessStatus",2);case "manualType"->t.put("needManuallyReceiveAward","true");case "signupType"->t.put("needSignUp","true");case "duplicate"->ApplicationHook.rows().put(tree("tree","TO_RECEIVE"));case "malformedMorpho"->t.put("taskExtProps",new JSONObject().put("TASK_MORPHO_DETAIL","garbage"));case "owner"->t.put("userId","B");case "event"->t.put("sendCampTriggerType","EVENT_TRIGGER");case "external"->t.optJSONObject("taskBaseInfo").put("title","邀请朋友");case "push"->t.optJSONObject("taskBaseInfo").put("appletType","PUSH_MODEL");}run("treeTasks");assert ApplicationHook.mutations==0:kind;}
  reset();ApplicationHook.home.remove("browseTaskList");ApplicationHook.home.remove("taskStatusList");ApplicationHook.home.remove("staticSceneGuideTaskList");ApplicationHook.rent.optJSONArray("taskDetailList").put(tree("rent","NOT_DONE"));run("treeTasks");assert ApplicationHook.mutations==0;
  for(String kind:new String[]{"scoreType","clickType","treeMissing","areaMissing","duplicateArea"}){reset();prepare("treeClean");switch(kind){case "scoreType"->ApplicationHook.home.put("purificationScore","100");case "clickType"->ApplicationHook.home.optJSONArray("trees").optJSONObject(0).put("remainPurificationClickNum",1.1);case "treeMissing"->ApplicationHook.home.optJSONArray("trees").optJSONObject(0).remove("treeCode");case "areaMissing"->ApplicationHook.home.optJSONObject("garbageMap").optJSONArray("type").optJSONObject(0).remove("subType");case "duplicateArea"->ApplicationHook.home.optJSONObject("garbageMap").optJSONArray("type").put(new JSONObject().put("subType","server-area"));}run("treeClean");assert ApplicationHook.mutations==0:kind;}
  for(String kind:new String[]{"countType","countMissing","limitFraction","finishedType","assistType","assist","external","game","pigeon","rent","duplicate","missingSpace","durationHuge"}){reset();JSONObject a=alc("a");ApplicationHook.alchemyRows().put(a);switch(kind){case "countType"->a.put("completedNum","0");case "countMissing"->a.remove("completedNum");case "limitFraction"->a.put("needCompleteNum",1.1);case "finishedType"->a.put("finishFlag","false");case "assistType"->a.put("shareAssist","false");case "assist"->a.put("shareAssist",true);case "external"->a.put("title","浏览后开通账户");case "game"->a.put("gameAppId","dynamic-game");case "pigeon"->a.put("templateId","zml_zmdabiaoge");case "rent"->a.put("templateId","zml_zmzl_cyz_erfang");case "duplicate"->ApplicationHook.alchemyRows().put(alc("a").put("title","changed"));case "missingSpace"->a.put("bizType","AD_TASK").put("logExtMap",new JSONObject().put("bizId","b"));case "durationHuge"->a.put("bizType","AD_TASK").put("logExtMap",new JSONObject().put("bizId","b").put("spaceCode","server_ad_duration=301"));}run("alchemyTasks");assert ApplicationHook.mutations==0:kind;}
  reset();prepare("alchemyTasks");ApplicationHook.drift=true;run("alchemyTasks");assert ApplicationHook.mutations==0;
  for(String kind:new String[]{"stateType","state2","tomorrow","tomorrowType","idType","rewardType"}){reset();switch(kind){case "stateType"->ApplicationHook.time.put("state","1");case "state2"->ApplicationHook.time.put("state",2);case "tomorrow"->ApplicationHook.time.put("tomorrow",true);case "tomorrowType"->ApplicationHook.time.put("tomorrow","false");case "idType"->ApplicationHook.time.put("templateId",5);case "rewardType"->ApplicationHook.time.put("rewardAmount","3");}run("alchemyTime");assert ApplicationHook.mutations==0:kind;}
  reset();ApplicationHook.timeState=3;run("alchemyTime");unknown("alchemyTime");
  reset();ApplicationHook.award.put("awardAvailable","true");run("alchemyNextDay");assert ApplicationHook.mutations==0;
  reset();ApplicationHook.award.put("awardAvailable",false);run("alchemyNextDay");assert ApplicationHook.mutations==0;ApplicationHook.award.put("awardAvailable",true);run("alchemyNextDay");assert ApplicationHook.mutations==1:"qualifies later today";
  for(String domain:new String[]{"treeTasks","alchemyTasks","alchemyTime","alchemyNextDay"})for(boolean uid:new boolean[]{false,true}){reset();prepare(domain);ApplicationHook.uidAfter=uid;ApplicationHook.cancelAfter=!uid;try{run(domain);throw new AssertionError("cancellation swallowed");}catch(TaskCancelledException expected){}assert ApplicationHook.mutations==1;UserIdMap.uid="A";TimeUtil.cancel=false;unknown(domain);}
  for(String interruption:new String[]{"cancel","uid","day"}){reset();prepare("treeTasks");TimeUtil.interruptAt=3000;TimeUtil.interrupt=interruption;try{run("treeTasks");assert interruption.equals("day");}catch(TaskCancelledException expected){assert !interruption.equals("day");}assert ApplicationHook.mutations==1&&count("RENT_GREEN_TASK_FINISH")==1;}
  reset();prepare("treeTasks");ApplicationHook.effect=false;run("treeTasks");unknown("treeTasks");MyUtils.offset=1;ApplicationHook.effect=true;run("treeTasks");assert ApplicationHook.mutations==1:"unknown remains frozen on next GMT8 day";
  reset();for(int i=0;i<45;i++)ApplicationHook.rows().put(tree("id"+i,"TO_RECEIVE"));run("treeTasks");assert ApplicationHook.mutations==40;run("treeTasks");assert ApplicationHook.mutations==40:"daily cap persists";MyUtils.offset=1;run("treeTasks");assert ApplicationHook.mutations==45;
  for(String kind:new String[]{"record","template","owner"})for(boolean sdk:new boolean[]{false,true}){reset();JSONObject task=sdk?alc("game-template").put("title","game").put("gameAppId","2060170000356601").put("recordId","game-record"):alc("zml_zmzl_cyz_erfang").put("title","\u6d4f\u89c8\u829d\u9ebb\u79df\u8d41").put("recordId","rent-record");ApplicationHook.alchemyRows().put(task);ApplicationHook.resultDrift=kind;run("alchemyTasks");assert Log.confirmed==0:kind;unknown("alchemyTasks");}
  for(String domain:new String[]{"treeTasks","treeClean","alchemyTasks","alchemyTime","alchemyNextDay"})for(String bad:new String[]{"garbage","missingDay","missingCount","badDay","future","badDate","badYear","badPadding","negative","fraction","overflow","countType"}){reset();prepare(domain);JSONObject budget=new JSONObject().put("day","2026-10-06").put("count",1);switch(bad){case "missingDay"->budget.remove("day");case "missingCount"->budget.remove("count");case "badDay"->budget.put("day","invalid");case "future"->budget.put("day","2099-10-01");case "badDate"->budget.put("day","2026-02-30");case "badYear"->budget.put("day","0000-01-01");case "badPadding"->budget.put("day","2026-1-1");case "negative"->budget.put("count",-1);case "fraction"->budget.put("count",1.2);case "overflow"->budget.put("count",41);case "countType"->budget.put("count","1");}RuntimeInfo.getInstance().putVerified("golden::sesameExtra::"+domain+"::budget",bad.equals("garbage")?"broken":budget.toString());run(domain);assert ApplicationHook.mutations==0&&SDK.opened==0:domain+bad;}
  for(String kind:new String[]{"rent","ad","sdk","delegate"}){reset();switch(kind){case "rent"->ApplicationHook.alchemyRows().put(alc("zml_zmzl_cyz_erfang").put("title","\u6d4f\u89c8\u829d\u9ebb\u79df\u8d41").put("recordId","rent-record"));case "ad"->ApplicationHook.alchemyRows().put(alc("source-ad").put("bizType","AD_TASK").put("title","\u6d4f\u89c8\u5e7f\u544a").put("logExtMap",new JSONObject().put("bizId","source-biz")));case "sdk"->ApplicationHook.alchemyRows().put(alc("game-template").put("title","game").put("gameAppId","2060170000356601").put("recordId","game-record"));case "delegate"->delegate();}ApplicationHook.effect=false;String domain=kind.equals("delegate")?"treeTasks":"alchemyTasks";run(domain);unknown(domain);int calls=ApplicationHook.calls.size(),http=SDK.opened;MyUtils.offset=1;ApplicationHook.effect=true;run(domain);assert calls==ApplicationHook.calls.size()&&http==SDK.opened:kind;}
  reset();TimeUtil.cancel=true;try{run("alchemyTime");throw new AssertionError();}catch(TaskCancelledException expected){}assert ApplicationHook.calls.isEmpty();
  System.out.println("PASS actual credit worker+real SDK wrapper: free rent/delegate dual-state readback, contracted/direct ads, four mapped SDK games, P2E captured pages/init/full waits/chunks/terminal progress, local concurrent tokens, redacted logs, typed same-record progress, real waits, durable unknown across days, valid budgets, UID/cancel/generation guards");
 }
}
'''

cache = Path(os.environ.get('GRADLE_USER_HOME', Path.home() / '.gradle')) / 'caches/modules-2/files-2.1/org.json/json'
jar = sorted(p for p in cache.glob('*/*/json-*.jar') if not p.name.endswith(('-sources.jar', '-javadoc.jar')))[-1]
env = dict(os.environ, JAVA_TOOL_OPTIONS='-Xms16m -Xmx192m')
properties = root / 'local.properties'
sdk_path = os.environ.get('ANDROID_HOME', os.environ.get('ANDROID_SDK_ROOT', ''))
if properties.exists():
    for line in properties.read_text(encoding='utf-8').splitlines():
        if line.startswith('sdk.dir='):
            sdk_path = line.split('=', 1)[1].replace('\\:', ':').replace('\\\\', '\\')
compile_sdk = re.search(r'compileSdk\s+(\d+)', (root / 'app/build.gradle').read_text(encoding='utf-8')).group(1)
android_jar = Path(sdk_path) / 'platforms' / ('android-' + compile_sdk) / 'android.jar'
if not android_jar.exists():
    android_jar = Path(sdk_path) / 'platforms' / ('android-' + compile_sdk + '.0') / 'android.jar'
assert android_jar.exists(), 'Android SDK required to verify production JSON checked exceptions'
with tempfile.TemporaryDirectory(prefix='sesame-credit-extras-') as tmp:
    files = [str(worker), str(source / pkg.replace('.', '/') / 'util/TaskCancelledException.java'), str(source / pkg.replace('.', '/') / 'data/task/TaskLifecycle.java'), str(source / pkg.replace('.', '/') / 'model/task/antGame/GameTask.java')]
    for suffix, body in stubs.items():
        f = Path(tmp) / ((pkg + '.' + suffix).replace('.', '/') + '.java')
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text('package ' + (pkg + '.' + suffix).rsplit('.', 1)[0] + ';\n' + body, encoding='utf-8')
        files.append(str(f))
    test_path = Path(tmp) / 'SesameCheck.java'
    test_path.write_text(test, encoding='utf-8')
    # Production worker/stub signatures compile against Android; runtime fixtures use the JVM JSON implementation.
    api_files = files[:4]
    for suffix, body in stubs.items():
        if suffix == 'hook.ApplicationHook':
            body = 'public class ApplicationHook {public static long getAlipayVersion(){return 1000;}public static String requestString(String m,String a){return "";}public static String requestString(String m,String a,int n,int d){return "";}}'
        if suffix == 'hook.AuthCodeHelper':
            body = 'public class AuthCodeHelper {public static String getAuthCode(String appId){return "";}}'
        f = Path(tmp) / 'api' / ((pkg + '.' + suffix).replace('.', '/') + '.java')
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text('package ' + (pkg + '.' + suffix).rsplit('.', 1)[0] + ';\n' + body, encoding='utf-8')
        api_files.append(str(f))
    subprocess.run(['javac', '-encoding', 'UTF-8', '-cp', str(android_jar), '-d', str(Path(tmp) / 'api-classes'), *api_files], check=True, env=env)
    subprocess.run(['javac', '-encoding', 'UTF-8', '-cp', str(jar), '-d', str(Path(tmp) / 'classes'), *files, str(test_path)], check=True, env=env)
    subprocess.run(['java', '-ea', '-cp', str(Path(tmp) / 'classes') + os.pathsep + str(jar), pkg + '.model.task.goldenbeans.SesameCheck'], check=True, env=env)

configuration = (worker.parent / 'goldenbeans.java').read_text(encoding='utf-8')
for key in ('sesameTreeTasks', 'sesameTreePurification', 'sesameAlchemyExtraTasks', 'sesameAlchemyTimeReward', 'sesameAlchemyNextDayReward'):
    assert re.search(r'new BooleanModelField\("' + key + r'",[^\n]+false\)', configuration), key + ' must default off'
assert 'catch (TaskCancelledException cancelled)' in configuration
